import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthCheck from "@/components/AuthCheck";
import ToastProvider from "@/components/ToastProvider"; // ✅ import new provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mediora cloud emr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthCheck>

        {children}
        <ToastProvider /> {/* ✅ client-side toast rendering */}
        </AuthCheck>
      </body>
    </html>
  );
}
